# [必需] 应用的唯一客户端 ID
client_id = ""

# [必需] 应用的名称
name = ""
handle = ""

# [必需] 应用的入口 URL。当商家点击应用时，他们将被重定向到此地址。
application_url = "https://k8s.fix-iterate.uk/shopify"
embedded = true

[build]
automatically_update_urls_on_dev = true

[auth]
  redirect_urls = [ "https://k8s.fix-iterate.uk/shopify" ]

[access_scopes]
  scopes = "write_products, write_inventory, write_orders, write_customers, write_draft_orders, write_payment_terms, write_returns, write_price_rules, write_discounts, write_marketing_events, write_shipping, write_locations, write_assigned_fulfillment_orders, write_merchant_managed_fulfillment_orders, write_third_party_fulfillment_orders, write_fulfillments, write_delivery_customizations, write_fulfillment_constraint_rules, write_themes, write_content, write_files, write_online_store_navigation, write_online_store_pages, write_metaobject_definitions, write_metaobjects, write_reports, read_analytics, read_audit_events, write_resource_feedbacks, customer_write_customers, customer_write_orders, write_customer_merge, write_customer_data_erasure, unauthenticated_write_checkouts, unauthenticated_write_customers, unauthenticated_read_product_listings, unauthenticated_read_content, read_markets, read_cash_tracking, read_customer_events, read_all_cart_transforms, write_cart_transforms, write_publications, write_product_listings"

[webhooks]
api_version = "2026-04"
[[webhooks.subscriptions]]
  topics = [
    "orders/create", "orders/cancelled", "orders/fulfilled", "orders/paid", "orders/delete",
  ]
  # 仅包含必要字段，减少 payload 大小
  include_fields = [
      "admin_graphql_api_id", "id", "created_at", "updated_at", "financial_status", "fulfillment_status", "name", "order_number", "currency", "email"
  ]
  uri = "/webhook"

[[webhooks.subscriptions]]
  topics = ["refunds/create"]
  include_fields = [
      "admin_graphql_api_id", "id", "order_id", "created_at", "processed_at",
      "transactions.id", "transactions.created_at", "transactions.amount", "transactions.status", "transactions.admin_graphql_api_id",
  ]
  uri = "/webhook"

# 其他通用事件
[[webhooks.subscriptions]]
  topics = [
    "app/uninstalled", "shop/update",
    "domains/create", "domains/update", "domains/destroy",
    "locations/create", "locations/update", "locations/delete"
  ]
  uri = "/webhook"
